spring:
  application:
    name: ulli-be

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect

supabase:
  url: https://uzortuupqijlxgzxtlch.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6b3J0dXVwcWlqbHhnenh0bGNoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzI5NTMzNywiZXhwIjoyMDYyODcxMzM3fQ.AEbtD-HfQBpV845JzP9_I0Mk2sxbnu2HyZD8sWCivEE
  bucket: images